### ISSUE TITLE
Typo in name

### ISSUE THREAD

**Issue by lanzone1** [agolca123/google-sheets-webhook#1]
When reviewing your template, we noticed that there is a typo in the name: `Google Sheets Weebhook`. Otherwise this looks good.

**Comment by agolca123** [comment]
Thanks for the warning, I updated it

**Comment by agolca123** [comment]
Thanks for the warning, I updated it

Andy Lanzone ***@***.***>, 13 Nis 2024 Cmt, 00:18 tarihinde
şunu yazdı:

**Comment by lanzone1** [comment]
Great, thanks!

Can you also update the `sha` value in [metadata.yaml](https://github.com/agolca123/google-sheets-webhook/blob/main/metadata.yaml) to match? It should be `531f97a05758506db1f25654c0b97ac5f0f0cde1`.

**Comment by agolca123** [comment]
I change it

**Comment by lanzone1** [comment]
Thanks!
